// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that suggests labels for columns in a data table.
 *
 * - labelColumns - A function that handles the column labeling process.
 * - LabelColumnsInput - The input type for the labelColumns function.
 * - LabelColumnsOutput - The return type for the labelColumns function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const LabelColumnsInputSchema = z.object({
  tableData: z.string().describe('A string representation of the data table.'),
  columnHeaders: z.array(z.string()).describe('An array of column headers for the data table.'),
});
export type LabelColumnsInput = z.infer<typeof LabelColumnsInputSchema>;

const LabelColumnsOutputSchema = z.object({
  columnLabels: z.array(z.string()).describe('An array of suggested labels for the columns.'),
});
export type LabelColumnsOutput = z.infer<typeof LabelColumnsOutputSchema>;

export async function labelColumns(input: LabelColumnsInput): Promise<LabelColumnsOutput> {
  return labelColumnsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'labelColumnsPrompt',
  input: {schema: LabelColumnsInputSchema},
  output: {schema: LabelColumnsOutputSchema},
  prompt: `You are an expert data scientist specializing in labeling data columns.

You will be provided with a data table and a set of column headers. Your task is to suggest appropriate labels for each column based on the data within the table.

Data Table:
{{{tableData}}}

Column Headers:
{{#each columnHeaders}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

Based on the data table and column headers, suggest a label for each column. Return the labels as an array of strings.
Ensure that the number of labels in the output matches the number of column headers in the input.

Output format: An array of strings representing suggested labels for each column.
`, // Ensure the AI returns an array of strings.
});

const labelColumnsFlow = ai.defineFlow(
  {
    name: 'labelColumnsFlow',
    inputSchema: LabelColumnsInputSchema,
    outputSchema: LabelColumnsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

